import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../providers/task_provider.dart';
import '../../providers/activity_provider.dart';

class CreateTaskScreen extends StatefulWidget {
  const CreateTaskScreen({super.key});

    @override
      State<CreateTaskScreen> createState() => _CreateTaskScreenState();
      }

      class _CreateTaskScreenState extends State<CreateTaskScreen> {
        final titleController = TextEditingController();
          final descriptionController = TextEditingController();
            final expController = TextEditingController();
              final rewardController = TextEditingController();

                String difficulty = 'Dễ';

                  void createTask() {
                      if (titleController.text.trim().isEmpty) return;

                          context.read<TaskProvider>().addTask(
                                title: titleController.text.trim(),
                                      description: descriptionController.text.trim(),
                                            difficulty: difficulty,
                                                  expReward: int.tryParse(expController.text) ?? 0,
                                                        rewardAmount: int.tryParse(rewardController.text) ?? 0,
                                                            );

                                                                context.read<ActivityProvider>().addActivity(
                                                                      title: 'Task Created',
                                                                            description: titleController.text.trim(),
                                                                                );

                                                                                    Navigator.pop(context);
                                                                                      }

                                                                                        @override
                                                                                          Widget build(BuildContext context) {
                                                                                              return Scaffold(
                                                                                                    appBar: AppBar(title: const Text('Tạo nhiệm vụ'), centerTitle: true),

                                                                                                          body: SingleChildScrollView(
                                                                                                                  padding: const EdgeInsets.all(24),

                                                                                                                          child: Column(
                                                                                                                                    children: [
                                                                                                                                                TextField(
                                                                                                                                                              controller: titleController,
                                                                                                                                                                            decoration: InputDecoration(
                                                                                                                                                                                            labelText: 'Tên nhiệm vụ',
                                                                                                                                                                                                            border: OutlineInputBorder(
                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                        ),

                                                                                                                                                                                                                                                                                    const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                              controller: descriptionController,
                                                                                                                                                                                                                                                                                                                            maxLines: 4,
                                                                                                                                                                                                                                                                                                                                          decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                          labelText: 'Mô tả',
                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                              DropdownButtonFormField<String>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initialValue: difficulty,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          items: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Dễ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Trung bình',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Khó',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChanged: (value) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        difficulty = value!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    labelText: 'Độ khó',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      controller: expController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'EXP thưởng',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    controller: rewardController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                labelText: 'Tiền thưởng',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 32),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: FilledButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPressed: createTask,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: const Text('Tạo nhiệm vụ'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        