// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHm10y3AkrJLTt-B4a0N84LYSmLFzZtGg',
    appId: '1:888213272879:web:40bfd42baef477c2c549da',
    messagingSenderId: '888213272879',
    projectId: 'life-rpg-app-94f1c',
    authDomain: 'life-rpg-app-94f1c.firebaseapp.com',
    storageBucket: 'life-rpg-app-94f1c.firebasestorage.app',
    measurementId: 'G-6KTVJVQ82R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRMGdwdFcz5tlXuQgaG0fwSHvZ1ZVgDY',
    appId: '1:888213272879:android:01dc933e70f75a42c549da',
    messagingSenderId: '888213272879',
    projectId: 'life-rpg-app-94f1c',
    storageBucket: 'life-rpg-app-94f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Og2jVDxwG5huWVyz7rFH5Dri5QaZ1qs',
    appId: '1:888213272879:ios:4c4b8a6a80427889c549da',
    messagingSenderId: '888213272879',
    projectId: 'life-rpg-app-94f1c',
    storageBucket: 'life-rpg-app-94f1c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Og2jVDxwG5huWVyz7rFH5Dri5QaZ1qs',
    appId: '1:888213272879:ios:4c4b8a6a80427889c549da',
    messagingSenderId: '888213272879',
    projectId: 'life-rpg-app-94f1c',
    storageBucket: 'life-rpg-app-94f1c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHm10y3AkrJLTt-B4a0N84LYSmLFzZtGg',
    appId: '1:888213272879:web:6c531a7da86dd83ec549da',
    messagingSenderId: '888213272879',
    projectId: 'life-rpg-app-94f1c',
    authDomain: 'life-rpg-app-94f1c.firebaseapp.com',
    storageBucket: 'life-rpg-app-94f1c.firebasestorage.app',
    measurementId: 'G-WGPLPZWJJ9',
  );
}
