// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRa84O6fbJ1IaiICo0kG-DWJuQTicP7Fs',
    appId: '1:578271500971:web:b371b146a71aa3ee41f5ee',
    messagingSenderId: '578271500971',
    projectId: 'liferpg-d0500',
    authDomain: 'liferpg-d0500.firebaseapp.com',
    storageBucket: 'liferpg-d0500.firebasestorage.app',
    measurementId: 'G-2JK9GFD7LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPxDJK_dFeI12aVyX5PCL-bOGiYGEzAA',
    appId: '1:578271500971:android:4088eac9c86f42e541f5ee',
    messagingSenderId: '578271500971',
    projectId: 'liferpg-d0500',
    storageBucket: 'liferpg-d0500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADVG4p3zm1wwotNWD79GmOZqfNvNvcWM',
    appId: '1:578271500971:ios:a061a7e24708508241f5ee',
    messagingSenderId: '578271500971',
    projectId: 'liferpg-d0500',
    storageBucket: 'liferpg-d0500.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADVG4p3zm1wwotNWD79GmOZqfNvNvcWM',
    appId: '1:578271500971:ios:a061a7e24708508241f5ee',
    messagingSenderId: '578271500971',
    projectId: 'liferpg-d0500',
    storageBucket: 'liferpg-d0500.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRa84O6fbJ1IaiICo0kG-DWJuQTicP7Fs',
    appId: '1:578271500971:web:06f68f23b76b5e6e41f5ee',
    messagingSenderId: '578271500971',
    projectId: 'liferpg-d0500',
    authDomain: 'liferpg-d0500.firebaseapp.com',
    storageBucket: 'liferpg-d0500.firebasestorage.app',
    measurementId: 'G-GRPWMDZQTC',
  );

}